#ifndef RECIPE_MANAGER_MEASUREMENTUNITS_H
#define RECIPE_MANAGER_MEASUREMENTUNITS_H

typedef enum {
    MILILITER,
    GRAM,
    PIECE,
    NONE
} MeasureUnit;

#endif //RECIPE_MANAGER_MEASUREMENTUNITS_H
